# tye application configuration file
# read all about it at https://github.com/dotnet/tye
#
# when you've given us a try, we'd love to know what you think:
#    https://aka.ms/AA7q20u
#
name: thewardrobe
services:
  - name: thewardrobe-gateway
    project: TheWardrobe.API.Gateway/TheWardrobe.API.Gateway.csproj
    bindings:
    - port: 5050
  - name: thewardrobe-account
    project: TheWardrobe.API.Account/TheWardrobe.API.Account.csproj
    bindings:
    - port: 5070
  - name: thewardrobe-item-catalog
    project: TheWardrobe.API.ItemCatalog/TheWardrobe.API.ItemCatalog.csproj
    bindings:
    - port: 5071
  - name: thewardrobe-clothes-classification
    image: clothes_classification_api
    bindings:
    - port: 5072
      containerPort: 5000
      protocol: http
  - name: thewardrobe-order
    project: TheWardrobe.API.Order/TheWardrobe.API.Order.csproj
    bindings:
    - port: 5073
  - name: thewardrobe-email-svc
    project: TheWardrobe.EmailSvc/TheWardrobe.EmailSvc.csproj
    bindings:
    - port: 5074
